### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by crutchcorn** [typeorm/typeorm.github.io#16]
I often find myself trying to search through the pages on this site. It would be nice to integrate some kind of search to the page for fast information finding

**Comment by pleerock** [comment]
on a single page, or on all pages? If on "all pages" its a bit problematic because it needs backend (but site is running using github static pages hosting), but on the page is easy solvable but less useful

**Comment by crutchcorn** [comment]
I did indeed mean global search, but was not thinking about hosting. Theoretically, there could be a switch to using something like a JS framework (react maybe) and using that to search everything (have the HTML files be global strings)... Idk.

**Comment by pleerock** [comment]
> theoretically, there could be a switch to using something like a JS framework (react maybe) and using that to search everything (have the HTML files be global strings)

In this case I'll need to load every page at once. Thats quite a lot and I don't think a good solution. Also not scalable at all because site content will only grow.

btw, I already developed a new site on vue (just wanted to try this framework) just didn't push it yet. Will do once 0.1.0 final is released

But definitely we need a good search functionality. Looks like I'll need to buy a hosting and place all content there

**Comment by Pedrock** [comment]
What do you think about something similar to the Objection.js documentation?

**Comment by crutchcorn** [comment]
From a code standpoint, I don't think that @pleerock would really want to maintain a huge HTML index of everything (which it seems like is being done there; admittedly only glanced at the docs code). I think it would be better to use Vue and host something small and simple for the job as suggested earlier

Ignoring the code for a second, I think that the search function should highlight the word that you're searching for when you click on a page with the information there. Otherwise it's very confusing

**Comment by aaronsturm** [comment]
This might be a good solution as it can possibly be free: https://www.algolia.com/for-open-source/

**Comment by crutchcorn** [comment]
Something that we ended up using for one of my projects (using Gatsby, admittedly) is by using Lunr. We're able to, at compile time, create an indexed file of all of the words in our posts that we then ship down to the client to be able to use client-side JS search. If Gatsby isn't wanted to be used, I know that GitHub Pages supports Jekyll:

https://learn.cloudcannon.com/jekyll/jekyll-search-using-lunr-js/

**Comment by OrkhanAlikhanov** [comment]
I forked the repo and created a [gitbook page](https://orkhan.gitbook.io/typeorm/) out of it with just a few clicks. It allows us to search easily. And will probably be indexed fine by search engines.

@pleerock, what do you think?

**Comment by piyushchauhan2011** [comment]
Now I almost use the orkhan static site instead of typeorm, it eases so many things for daily referencing of documentation. Thank you @OrkhanAlikhanov

**Comment by piyushchauhan2011** [comment]
I think if it's (orkhan typeorm website) referenced in the main page of github readme, it would help new comers rather than wasting time on clicking and looking documentation

**Comment by Kevga** [comment]
@OrkhanAlikhanov Could you either update the gitbook page or take it offline? It comes up in the first few search results for TypeORM documentation and contains outdated information.

**Comment by OrkhanAlikhanov** [comment]
Hi, I think it would better to add redirections, I'll try to add that if gitbook allows

**Comment by OrkhanAlikhanov** [comment]
GitBook is very tight, couldn't find a way to add redirects. I don't think it's good idea to take the gitbook page offline as it's still being used unless typeorm team specifically asks me to do so. I installed a GitHub App to auto sync my fork with typeorm's, so it should stay up-to-date always.

**Comment by PiotrekPKP** [comment]
> GitBook is very tight, couldn't find a way to add redirects. I don't think it's good idea to take the gitbook page offline as it's still being used unless typeorm team specifically asks me to do so. I installed a GitHub App to auto sync my fork with typeorm's, so it should stay up-to-date always.

Yeah, I use it pretty often. If it's updated I think it should stay online :)

**Comment by Woodz** [comment]
Where can we raise bugs with the GitBook docs being outdated/incorrect? Bug https://github.com/typeorm/typeorm/issues/7972 mentions a documentation bug that is still present in the GitBook

> Optional RemoveOptions can be passed as parameter for remove and delete.

This quote is incorrect - they cannot be passed to `delete`

**Comment by OrkhanAlikhanov** [comment]
@Woodz gitbook fork is in sync with typeorm master branch. You can make a PR to update original docs in typeorm repo. It will be reflected in both docs. Here is the link to that line in docs: https://github.com/typeorm/typeorm/blob/83567f533482d0170c35e2f99e627962b8f99a08/docs/repository-api.md?plain=1#L419
