### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by sirgallifrey** [typeorm/typeorm.github.io#22]
Hello, I'm getting cert errors trying to use the website, I don't know if it is some github problem or something  you people can fix, but I'm posting anyway just in case...

![typeorm](https://user-images.githubusercontent.com/2331645/47522857-07481700-d86d-11e8-9079-b6e437ad8475.png)

Looks like Common name is set to *.github.com while should be typeorm.io

Here is Brave showing the Cert, sorry for pt-br lang
> Este site não pode ser carregado devido a um erro de certificado: https://typeorm.io/#/
net::ERR_CERT_COMMON_NAME_INVALID
Emitido Para
Nome Comum (CN): *.github.com
Número de Série: 09:97:52:34:E8:32:42:49:9B:F5:D1:0B:72:CA:95:1E
Emitido Por
Nome Comum (CN): DigiCert SHA2 High Assurance Server CA
Período de Validade
Começa Em: Sun Mar 19 2017 21:00:00 GMT-0300 (Horário Padrão de Brasília)
Expira Em: Tue Apr 07 2020 09:00:00 GMT-0300 (Horário Padrão de Brasília)
Impressão Digital: sha256: 6f:ec:26:88:81:80:b7:cc:99:00:02:33:0d:24:3a:b1:7b:e8:d4:48:95:a7:8e:52:2e:ac:dc:92:36:d5:3f:cf

**Comment by pleerock** [comment]
why are you trying to access https and not http?

**Comment by sirgallifrey** [comment]
Why would I not use it when available?  Also I prefer to send https links to my colleagues, thats how I noticed the broken certificate. And the https link is in the readme.md
![typeormreadme](https://user-images.githubusercontent.com/2331645/47650451-0f4ed200-db5f-11e8-949f-d73867a9fa80.png)

Don't take me wrong, I'm not one of those people like "https or nothing!" I just noticed the problem and thought it would be good to ping the members of the project just in case. :)

**Comment by pleerock** [comment]
I probably need help to setup it with a github...

**Comment by MANTENN** [comment]
The HTTPS link also contains an invalid certificate.

**Comment by miensol** [comment]
For me the easiest way to have https for github pages is using https://cloudflare.com. Perhaps it would work for you as well.

**Comment by pleerock** [comment]
This should be fixed now.
