### ISSUE TITLE
Move DOCS to this repository

### ISSUE THREAD

**Issue by johannesschobel** [typeorm/typeorm.github.io#27]
Dear TypeORM team,

related to this issue here: https://github.com/typeorm/typeorm/issues/3746 i thought, that it may be better, to move the `/docs` folder from `typeorm/typeorm` to this package. What do you think about this?

This way, we could have all the docs (and the corresponding localization stuff) in one single repository?

Obviously, changes to the code (and therefore the docs) are more complicated, because you would need to push into two separate repos..

All the best

**Comment by pleerock** [comment]
> Obviously, changes to the code (and therefore the docs) are more complicated, because you would need to push into two separate repos..

yes and thats why we don't want to do this.

**Comment by johannesschobel** [comment]
Dear @pleerock ,
yeah, i can fully understand this! I am not sure, if i would do this either :laughing: ... Anyways, thanks a lot for your time and patience.. All the best
