### ISSUE TITLE
add dark mode option on TypeORM homepage

### ISSUE THREAD

**Issue by EdTosoy** [typeorm/typeorm.github.io#41]
**Issue type:**

[X] Documentation Issue

maybe at least just like this,  or something better

![image](https://user-images.githubusercontent.com/68400105/96259869-c95fd280-0ff0-11eb-924c-e0d0de9b43e9.png)

**Comment by imnotjames** [comment]
Transferred issue to the correct repo.

**Comment by ranjan-purbey** [comment]
Related #61
Maybe we can close this issue
