### ISSUE TITLE
Suggestion: a more scalable documentation solution

### ISSUE THREAD

**Issue by mickrip** [typeorm/typeorm.github.io#5]
Perhaps it might be better if a static site generator was used - something a little more maintainable?

**Comment by pleerock** [comment]
Hi. Yes, first I wanted to use static site generator then decided to use raw html+javascript etc. I also like to support site written in markdown, however its not scalable. Going with raw html+javascript is more scalable. I afraid in some point I'll need to more advanced javascript functionality that will be hardly achieved via static site generators.

**Comment by pleerock** [comment]
now its veujs site loading markdown docs directly from typeorm repository
