### ISSUE TITLE
TS file not compile

### ISSUE THREAD

**Issue by shivamanhar** [typeorm/typeorm.github.io#51]
I try to run command for compile my ts file to js. used following code.

`node src/app`

They return error 

`error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.`

I am using node 14.17.4. what is solution

[screen shot](https://prnt.sc/1qvflqg)

**Comment by AlexMesser** [comment]
This is a documentation repo. If you still have an issue, please open it in the https://github.com/typeorm/typeorm repo.
