### ISSUE TITLE
Documentation links not working

### ISSUE THREAD

**Issue by boyanstanchev** [typeorm/typeorm.github.io#53]
After the most recent changes from **Connection** to **DataSource**  the docs for 
- connection-api.md
- connection-options.md
- using-ormconfig.md 
- connection.md

are not working.

**Comment by pleerock** [comment]
it's due to yesterday's release of `0.3.0`. Now we need to update the docs and website. Please feel free to PR if you have!

**Comment by pleerock** [comment]
fixed
