### ISSUE TITLE
Any more information around migrations?

### ISSUE THREAD

**Issue by mildfuzz** [typeorm/typeorm.github.io#7]
Migration documentation is a little light. Diving into the code there are a lot of classes involved, understanding would be greatly improved by more documentation

**Comment by pleerock** [comment]
yes, agree. Overall state of docs isn't good enough, not only migrations part. There are lot of things and details you can find from samples or experimenting with code which aren't documented. I need some help from contributors here.

**Comment by mildfuzz** [comment]
some use cases and examples might help a contributor understand enough to have a crack at writing docs for all the various schemas buried within the architecture,

**Comment by pleerock** [comment]
latest docs on migrations are improved quite a lot
